{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: policy-report-ui-cluster-config
  namespace: {{ include "policyreporter.namespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ printf "http://%s:%d" (include "policyreporter.fullname" .) (.Values.service.port | int) | b64enc }}
  {{- if index .Values "kyverno-plugin" "enabled" }}
  {{- $host := printf "http://%s-kyverno-plugin:%d/api" .Release.Name ((index .Values "kyverno-plugin" "service" "port") | int) }}
  plugin.kyverno: {{ (printf "{\"host\":\"%s\", \"name\":\"kyverno\"}" $host) | b64enc }}
  {{- end }}
  {{- if index .Values "trivy-plugin" "enabled" }}
  {{- $host := printf "http://%s-trivy-plugin:%d/api/vulnr" .Release.Name ((index .Values "trivy-plugin" "service" "port") | int) }}
  plugin.trivy: {{ (printf "{\"host\":\"%s\", \"name\":\"Trivy Vulnerability\"}" $host) | b64enc }}
  {{- end }}
{{- end }}