loki:
  #host: http://localhost:3100
  minimumPriority: "debug"
  skipExistingOnStartup: true

elasticsearch:
  #host: http://localhost:9200
  minimumPriority: "warning"
  skipExistingOnStartup: true

slack:
  #webhook: http://localhost:9200
  minimumPriority: "error"
  skipExistingOnStartup: true
  
discord:
  #webhook: https://discord.com/api/webhooks/815967448930844703/I_YQam6B6UpBmc4BT6_-GZG_uriqV27gwyDgxnSdUPTeMxIRsD1lS3VXwTlDMecQ7Ezz
  minimumPriority: "success"
  skipExistingOnStartup: true
  
teams:
  #webhook: https://frankjogeleitweb.webhook.office.com/webhookb2/4f615fe7-6a66-4469-a21b-2e32bca95750@ebbd6124-b361-4718-92e6-34faba9e95b5/IncomingWebhook/ff7b16c5cb1b4b41919b49501458504f/0b55ddc9-81bb-429c-9769-495feeb7405e
  minimumPriority: "warning"
  skipExistingOnStartup: true

ui:
  host: http://localhost:8082
  minimumPriority: "warning"
  skipExistingOnStartup: true
