apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-config
  namespace: {{ include "ui.namespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
  config.yaml: |-
    clusters:
    - name: {{ .Values.clusterName | quote }}
      host: http://{{ include "ui.policyReportServiceName" . }}:{{ .Values.policyReporter.port }}
      {{- if or .Values.global.basicAuth.username .Values.global.basicAuth.secretRef }}
      basicAuth:
        username: {{ .Values.global.basicAuth.username }}
        password: {{ .Values.global.basicAuth.password }}
        secretRef: {{ .Values.global.basicAuth.secretRef }}
      {{- end }}
      {{- if or .Values.plugins.kyverno .Values.global.plugins.kyverno }}
      plugins:
      - name: kyverno
        host: http://{{ include "ui.kyvernoPluginServiceName" . }}:{{ .Values.kyvernoPlugin.port }}
      {{- end }}
    {{- with .Values.clusters }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    
    ui:
      {{- with .Values.labelFilter }}
      labelFilter:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.defaultFilter }}
      defaultFilter:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    logging:
      enabled: {{ .Values.logging.enabled }}
      encoding: {{ .Values.logging.encoding }}
      logLevel: {{ .Values.logging.logLevel }}
      development: {{ .Values.logging.development }}

    server:
      overwriteHost: {{ .Values.server.overwriteHost }}
      mode: release