apiVersion: v2
name: policy-reporter-alpha
description: |
  Policy Reporter watches for PolicyReport Resources.
  It creates Prometheus Metrics and can send rule validation events to different targets like Loki, Elasticsearch, Slack or Discord

type: application
version: 3.0.0-alpha
appVersion: 3.0.0-alpha

icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
home: https://kyverno.github.io/policy-reporter
sources:
  - https://github.com/kyverno/policy-reporter
maintainers:
  - name: Frank Jogeleit

dependencies:
  - name: monitoring
    condition: monitoring.enabled
    version: "2.8.1"
  - name: ui
    condition: ui.enabled
    version: "2.10.2"
  - name: kyvernoPlugin
    condition: kyvernoPlugin.enabled
    version: "1.6.2"
