name: Docs

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Generate
        run: cd frontend && npm run generate

      - name: Copy Helm files
        run: |
          cp index.yaml ./docs/index.yaml
          cp artifacthub-repo.yml ./docs/artifacthub-repo.yml


      - name: Deploy
        uses: EndBug/add-and-commit@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: docs
          branch: gh-pages
          message: generate docs
          push: true

