name: release

on:
  push:
    branches:
      - 'alpha'

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.10.3
      - name: Set Tag
        run: |
          set -e
          echo "TAG=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Set version
        run: |
          set -e
          echo "APP_VERSION=3.0.0.alpha-${{ env.TAG }}" >> $GITHUB_ENV
          echo "CHART_VERSION=policy-reporter-alpha-${{ env.TAG }}" >> $GITHUB_ENV
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 #v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          linting: off
          charts_dir: charts
          app_version: ${{ env.APP_VERSION }}
          chart_version: ${{ env.CHART_VERSION }}
